[custom.all.irw-core]
type = "local"
path = "irw-core"
ipkg = "irw-core.ipkg"
test = "test/test.ipkg"

[custom.all.irw-libs]
type = "local"
path = "irw-libs"
ipkg = "irw-libs.ipkg"
test = "test/test.ipkg"

[custom.all.irw-tt]
type = "local"
path = "irw-tt"
ipkg = "irw-tt.ipkg"

#------------------------------------------------------------
#   Custom Dependencies
#------------------------------------------------------------

[custom.all]
algebra.commit         = "latest:main"
array.commit           = "latest:main"
hedgehog.commit        = "latest:main"
refined.commit         = "latest:main"
