[custom.all.irw-core]
type = "local"
path = "core"
ipkg = "irw-core.ipkg"
test = "test/test.ipkg"

#------------------------------------------------------------
#   Custom Dependencies
#------------------------------------------------------------

[custom.all]
algebra.commit         = "latest:main"
array.commit           = "latest:main"
refined.commit         = "latest:main"
