---
name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build ${{ github.repository }} with Idris2 latest
    runs-on: ubuntu-latest
    env:
      PACK_DIR: /root/.pack
    strategy:
      fail-fast: false
    container: ghcr.io/stefan-hoeck/idris2-pack:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build libs
        run: pack install irw-libs
      - name: Run test libs
        run: pack test irw-libs -n 1000
      - name: Build core
        run: pack install irw-core
      - name: Run test core
        run: pack test irw-core -n 1000
      - name: Build tt
        run: pack install irw-tt
